# Makefile
# IFJ20 compiler
# Author: František Nečas (xnecas27), FIT BUT

.PHONY: clean

CC = gcc
CFLAGS = -std=c11 -pedantic -Wall -Wextra

mutable_string.o: mutable_string.c mutable_string.h

clean:
	rm -f *.o
